### ISSUE TITLE
Windows newline characters detected

### ISSUE THREAD

**Issue by heat23** [heatware/phpbb-global-feedback-plugin#27]
When submitting the plugin to phpBB, it gave out this validation error:

Validation: FAILED 
Fatal: 4, Error: 0, Warning: 0, Notice: 0 

Test results for extension:
Fatal error: Detected windows style newlines instead of UNIX newlines in /HeatWare/integration/acp/main_module.php
Fatal error: Detected windows style newlines instead of UNIX newlines in /HeatWare/integration/cron/task/HeatWareSync.php
Fatal error: Detected windows style newlines instead of UNIX newlines in /HeatWare/integration/event/listener.php
Fatal error: Detected windows style newlines instead of UNIX newlines in /HeatWare/integration/language/en/info_acp_lang.php

**Comment by derekheld** [comment]
I think we're ok on this. I fixed my local copy where I packaged the release.
