### ISSUE TITLE
Handle case where connected HeatWare account is deleted

### ISSUE THREAD

**Issue by heat23** [heatware/phpbb-global-feedback-plugin#30]
It is possible that after the user's forum profile is connected with HeatWare, that their heatware account is deleted. We should disassociate the forum account with Heatware if this happens (i.e. not display any stats)

**Comment by derekheld** [comment]
I think the easiest way for me to handle this would be to zero out the heatware ID associated with the user if I get a 404 back. It would force the sync task to perform a lookup by email again for any future sync runs.

The code that displays the feedback also looks for a heatware ID to be present already. So no ID means "Not Available" will be shown for feedback.
